version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: crypto-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: crypto_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - crypto-network

  postgres:
    image: postgres:16-alpine
    container_name: crypto-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: crypto_analytics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crypto-network

  redis:
    image: redis:7-alpine
    container_name: crypto-redis
    restart: unless-stopped
    command: redis-server --requirepass password123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - crypto-network

networks:
  crypto-network:
    driver: bridge

volumes:
  mongodb_data:
  postgres_data:
  redis_data:
