[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run compile"

[deploy]
startCommand = "npm run start:backend"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"
